name: Send Commit Message to Discord

on:
  push:
    branches: [ main ]

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          # Method 1: Use actual newlines instead of \n
          CONTENT="**New Commit:**
          
          **$COMMIT_MESSAGE**
          [View Commit]($COMMIT_URL)
          
          Committed by *$COMMIT_AUTHOR*"

          PAYLOAD=$(jq -n \
            --arg content "$CONTENT" \
            --arg username "GitHub Bot" \
            '{username: $username, content: $content}')

          RESPONSE=$(curl -s -H "Content-Type: application/json" \
                      -X POST \
                      -d "$PAYLOAD" \
                      "$DISCORD_WEBHOOK")

          echo "Discord response: $RESPONSE"
